//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dF.Commons.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dF.Commons.Exceptions.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be equal to {1}.
        /// </summary>
        public static string ArgumentException_CantBeEqualTo {
            get {
                return ResourceManager.GetString("ArgumentException_CantBeEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid {0} confirmation token.
        /// </summary>
        public static string ArgumentException_InvalidConfirmationToken {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid {0}.
        /// </summary>
        public static string ArgumentException_ProvideValidValue {
            get {
                return ResourceManager.GetString("ArgumentException_ProvideValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a(n) {0}.
        /// </summary>
        public static string ArgumentException_ProvideValue {
            get {
                return ResourceManager.GetString("ArgumentException_ProvideValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already taken.
        /// </summary>
        public static string DuplicateEntity {
            get {
                return ResourceManager.GetString("DuplicateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} is already associated with this {1}.
        /// </summary>
        public static string DuplicateEntity_AlreadyAssociatedWith {
            get {
                return ResourceManager.GetString("DuplicateEntity_AlreadyAssociatedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already taken with the same {1}.
        /// </summary>
        public static string DuplicateEntity_WithField {
            get {
                return ResourceManager.GetString("DuplicateEntity_WithField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already taken with {1} equal to {2}.
        /// </summary>
        public static string DuplicateEntity_WithFieldEqualTo {
            get {
                return ResourceManager.GetString("DuplicateEntity_WithFieldEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is locked because of a dependency to {1}.
        /// </summary>
        public static string EntityLockedException_ExistingDependableEntity {
            get {
                return ResourceManager.GetString("EntityLockedException_ExistingDependableEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is locked.
        /// </summary>
        public static string EntityLockedExpection {
            get {
                return ResourceManager.GetString("EntityLockedExpection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} found with the provided ID.
        /// </summary>
        public static string EntityNotFoundException_NoRecordFoundByProvidedID {
            get {
                return ResourceManager.GetString("EntityNotFoundException_NoRecordFoundByProvidedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either no {0} found with the provided ID or User is not allowed to access the Resource.
        /// </summary>
        public static string EntityNotFoundException_NoRecordFoundByProvidedIDOrUnauthorize {
            get {
                return ResourceManager.GetString("EntityNotFoundException_NoRecordFoundByProvidedIDOrUnauthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} found equal to {1}.
        /// </summary>
        public static string EntityNotFoundException_NoRecordFoundEqualTo {
            get {
                return ResourceManager.GetString("EntityNotFoundException_NoRecordFoundEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} Found.
        /// </summary>
        public static string EntityNotFoundException_NoRecordsFound {
            get {
                return ResourceManager.GetString("EntityNotFoundException_NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find {0} for removal.
        /// </summary>
        public static string EntityNotFoundException_NoRecordsFoundForDelete {
            get {
                return ResourceManager.GetString("EntityNotFoundException_NoRecordsFoundForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find {0} in order to update.
        /// </summary>
        public static string EntityNotFoundException_NoRecordsFoundForUpdate {
            get {
                return ResourceManager.GetString("EntityNotFoundException_NoRecordsFoundForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happend while adding a(n) {0}.
        /// </summary>
        public static string Exception_CreateEntityError {
            get {
                return ResourceManager.GetString("Exception_CreateEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happend while deleting a(n) {0}.
        /// </summary>
        public static string Exception_DeleteEntityError {
            get {
                return ResourceManager.GetString("Exception_DeleteEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while retrieving {0}.
        /// </summary>
        public static string Exception_GetEntitiesError {
            get {
                return ResourceManager.GetString("Exception_GetEntitiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while retrieving a(n) {0}.
        /// </summary>
        public static string Exception_GetEntityError {
            get {
                return ResourceManager.GetString("Exception_GetEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happend while updating a(n) {0}.
        /// </summary>
        public static string Exception_UpdateEntityError {
            get {
                return ResourceManager.GetString("Exception_UpdateEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} found equal to {1}.
        /// </summary>
        public static string KeyNotFoundException_NoKeyFoundEqualTo {
            get {
                return ResourceManager.GetString("KeyNotFoundException_NoKeyFoundEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to perform this Action.
        /// </summary>
        public static string UnauthorizedAccess_ActionNotAllowed {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_ActionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough permissions for {0}.
        /// </summary>
        public static string UnauthorizedAccess_NoEnoughPermissions {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_NoEnoughPermissions", resourceCulture);
            }
        }
    }
}
