//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puzzle.Models.InMemory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBSources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBSources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Puzzle.Models.InMemory.DBSources", typeof(DBSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\..\Databases\JSON.DB\cypher.json.
        /// </summary>
        internal static string RelativePathToCypher {
            get {
                return ResourceManager.GetString("RelativePathToCypher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\..\Databases\JSON.DB\values.json.
        /// </summary>
        internal static string RelativePathToCypherScheme {
            get {
                return ResourceManager.GetString("RelativePathToCypherScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\..\Databases\JSON.DB\words.json.
        /// </summary>
        internal static string RelativePathToPuzzleWords {
            get {
                return ResourceManager.GetString("RelativePathToPuzzleWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\..\..\Databases\JSON.DB\base.json.
        /// </summary>
        internal static string RelativePathToReplacementRules {
            get {
                return ResourceManager.GetString("RelativePathToReplacementRules", resourceCulture);
            }
        }
    }
}
